---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
  - secure: Dqubghoe1gKXweKnv+8/+sxjW2coL00Zzhzamv0RS66aQ4DZ92yvvCRiyKmCLUX7d884djDLWCZQEaeMFd7upGqnb8ryZoPwp5qiyCTTAE83doU1JSM+qh4fZJbJ4MoM5cxygvSucfcHV6NdUvE1sFsqmYyRHotkhj7UNMi5S9oirL0NRJlQvntGLggQXqfP7hOFuXQkb6snLzZqJaGMFl5+8hzbXDr7hyGo6428fKupW5EyAEHj5JHfdh6HurH10/Tn4f9L9irpl8Gl0VLdRwrE5bePCwIFWO9+qnQxbXkYz8oQIoK4sAt4Al/KoU4gSAC8c+khx0gEHORv5YFbAG9lMfIzd193Roc2nsqa/orZ4P9v6Yqcsdx0w6n62bqyPX3a3NyaBC+J0IbOwvp4lC3+Q+Oe2kF75UyA9maM+ndcXIAvuQm5KVB8dFm+E60UvhFQgUTsz+Om0NE9R+BwZZLnGjphPzDaV+628zP0RSogXB3RG4hLef7036+zozGfQHw9DAJgrIZaIIE3DbQz6DdMEEI8dpyWTTr1wtvUr8UGIB3ZW+7KXDAkJIguaCM4jxmQbnXvRqElDXCD9o3FrOT6pc90hsI6ImcapVLIFMEtWp3/c8c0MIM8Xm77fYflZy0R7FUy6QU0QeKXLF0NyW8g57eIS9GRCuKH8Zv6i1s=
  - secure: s5BCpjE1KhQiJ2rffMonzWoLL3vfqHgkJancqf5J7Yd1qfRYNOB/W4XyOg4/1rOZV34mAD9brognT1tpfVRij/sNag0EZSHCPsklM4vI2/AQXcZ/W2KEifBzm7lZ1C5ATuZ+zqBELEy7vs4A1/1+Jl5T8uO5lQaDxG8F/utpepFVBZ3M9cfi3F75HxPl8IXKndi1lRIe91n/MMsO0j5gR8fd9ZVBzIC6Py2QcQnS2fEvWBfhHHrWM9QnWWzyuYwR5nT4/So6pdgEW0voujH5TPP3YaWZLSSD0zW3dpIZWE3TEoMGj10c6y+NKyJBkgaH5ihHs5mxhb2W0oZJgSXToeKr6PTjVK48moK/9YOMSvTBVgKKZuPrBGttU9v0XRNnNfN3M3NVnZ+L6HCJixD/hdN4C8bDGrI+t11tHYRy7QAYmS8sqIPnx5QA4cPvH+8JjJnseSXQkESAVOMUj0I8u0q4kujqPNUF+bHKe24NO4a8qP2ZpafUn1NH5xZaIchdJNMZykI4v3Afvo0WIU1JrQaViZu1TM6DlIiFmcsz1/dkILr5QIrIEVto+9UYu2upBcSE0V71le68xwLVUdaLjUCeku2xIs+Ws9nR9RCq1e7hgnxdGtdKoeoulKghMVLewu0pLOgBxIZ7GZ+tRy9YHynxmJtQ1T881fMfDjDaijE=
  - secure: JMPVcX68+mizaVhOfqan/Dy552Khw4ULenp9MBv0ca8aHOYq4ibcetGxhcY27BR0HO8C1stITslkm3xWmC7alB7JDvmzjlcGeGGKUMilUdGpl7mMzou8A81eH4yF0uEZC0gmbAToLWXpepQhTa+v80Sm9wyCvMTJXzAJ20PZpaB+QNY90FaVk3XrxJBMhNKRpziBL/VaYFr+/mdtm6zxG0/cDAQEpygahXEW/5TWcOEHAmA20IurHbBxICZwk7Omj52+Q0qCzkS/0HVZ84g/mtPHPga0iB0K2NAAu9Of/OskQXHm/ORYKIT6atb0BftX8Jr53TYlHKHI7ofojObrZr3B/2UVuBWZ7qELrk5CIPoqpTeCqM54uetF4/X+ZbzF6ESVz5Zal53XzibSelwqYdIiWdl2yBYxtnSoCmGMikPosgPsvgoeyZldZxP77N/R0LaMg/ywL7sfBtx/c29sbkaFdcTvbxtW6ioGcG7PF56El9NVNbgd9WHpT0Axgm3QBWRIcAvwMu629VzL/ShGT7JgYB9I1q6jkkdMR/33Sqse7dtTSGnfx5vkiGw7iwxDC8Ed3QXjgSWazscSsScDgqPbhgO6ApGqB7sRH5Fr2v5tNU8uHvoOeVa9UwaCJcbC96RjW+E2Qc4CKSGQWlqNbRVQSxsqeSmUCWAafxC2CRw=
  matrix:
    # Provide a list of GLPI version to build
    - GLPI_VERSION="9.3.0"

script:
  - export VCS_REF=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_COMMIT; else echo $TRAVIS_PULL_REQUEST_SHA; fi)
  - export VCS_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

  # Download tools shim.
  - wget -O ${PWD}/_tools.sh https://gist.github.com/Wolvverine/cd03f29d68600c8850aeed8fe2b3d464/raw

  # 
  # Build docker image
  #
  - ${PWD}/build.sh

  #
  ## Run tests
  #
  - ${PWD}/tests.sh && touch _test_ok

  #
  # Deploy
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a  -n "$DOCKERHUB_REGISTRY_USERNAME" -a -n "$DOCKERHUB_REGISTRY_PASSWORD" ]'
  - '[ -f _test_ok ] && ${PWD}/deploy.sh'
