# First stage : download glpi + build it
FROM composer:latest AS build_glpi

ARG GLPI_VERSION
ARG GLPI_PATHS_ROOT=/var/www

RUN mkdir -p "${GLPI_PATHS_ROOT}"
RUN curl -v --fail -o glpi.tgz -L "https://github.com/glpi-project/glpi/releases/download/${GLPI_VERSION}/glpi-${GLPI_VERSION}.tgz" \
    && tar -xzf glpi.tgz --strip 1 --directory ${GLPI_PATHS_ROOT}

WORKDIR "${GLPI_PATHS_ROOT}"

# Second stage : build final image
FROM php:8.4-fpm-alpine

LABEL maintainer='Michał Panasiewicz <wolvverinepld@gmail.com>'

ARG GLPI_VERSION
ARG PHP_XDEBUG=no

ENV GLPI_VERSION="${GLPI_VERSION}"
ENV GLPI_PATHS_ROOT="/var/www"
ENV GLPI_PATHS_PLUGINS="/var/www/plugins"
ENV GLPI_REMOVE_INSTALLER=no
ENV GLPI_CHMOD_PATHS_FILES=no
ENV GLPI_INSTALL_PLUGINS=''

ENV PHP_XDEBUG="${PHP_XDEBUG}"
ENV PHPFPM_XDEBUG_IDE_KEY='Docker'
ENV PHPFPM_XDEBUG_CLIENT_PORT=9003
ENV PHPFPM_XDEBUG_CLIENT_HOST='host.docker.internal'

ENV PHP_UPLOAD_MAX_FILESIZE=16m
ENV PHP_MAX_EXECUTION_TIME=3600
ENV PHP_POST_MAX_SIZE=20M
ENV PHP_OPCACHE_MEM_CONSUMPTION=256
ENV PHP_MEMORY_LIMIT=64M
ENV PHP_MAX_INPUT_VARS=3000

ENV PHPFPM_PM=dynamic
ENV PHPFPM_PM_MAX_CHILDREN=30
ENV PHPFPM_PM_START_SERVERS=4
ENV PHPFPM_PM_MIN_SPARE_SERVERS=4
ENV PHPFPM_PM_MAX_SPARE_SERVERS=8
ENV PHPFPM_PM_PROCESS_IDLE_TIMEOUT=120s
ENV PHPFPM_PM_MAX_REQUEST=2000

ENV LANG='en_US.UTF-8'
ENV LC_ALL='en_US.UTF-8'


# Upgrade and install dependencies
RUN set -ex; \
    apk list --installed && apk update && apk upgrade
RUN set -ex; \
    PHP_XDEBUG=$(echo "${PHP_XDEBUG}" | tr '[:upper:]' '[:lower:]') ; \
    apk --no-cache add \
      curl \
      nginx \
      fping \
      graphviz \
      iputils \
      net-snmp-libs \
      py3-pip \
      supervisor \
      tar \
      tzdata \
    ; \
    pip3 install --break-system-packages \
      jinjanator \
    ; \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        autoconf \
        bzip2-dev \
        coreutils \
        curl-dev \
        freetype-dev \
        icu-dev \
        libevent-dev \
        libjpeg-turbo-dev \
        libmcrypt-dev \
        libxml2-dev \
        libzip-dev \
        libpng-dev \
        net-snmp-dev \
        openldap-dev \
        pcre-dev \
        imagemagick-dev \
        linux-headers \
    ; \
    docker-php-source extract ; \
    docker-php-ext-configure gd --with-freetype=/usr --with-jpeg=/usr; \
    docker-php-ext-configure ldap ; \
    docker-php-ext-install \
       bz2 \
       exif \
       gd \
       intl \
       ldap \
       mysqli \
       opcache \
       snmp \
       soap \
       zip \
    ; \
    pecl install apcu && docker-php-ext-enable apcu ; \
    pecl install xmlrpc-1.0.0RC3 && docker-php-ext-enable xmlrpc ; \
    if [ "$PHP_XDEBUG" = "yes" ] ; then \
        pecl install xdebug-3.3.2 && docker-php-ext-enable xdebug ; \
    else \
        echo "PHP_XDEBUG is not build - set PHP_XDEBUG to yes." ; \
    fi ; \
    docker-php-source delete ; \
    runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
            | tr ',' '\n' \
            | sort -u \
            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )"; \
    apk add --virtual .nextcloud-phpext-rundeps $runDeps; \
    apk del .build-deps ; \
    mkdir -p /run/nginx ; \
    find "${GLPI_PATHS_ROOT}" -mindepth 1 -maxdepth 1 -not -name '.*' -and -not -name '..' | xargs rm -rfv ;
RUN rm -f /usr/local/etc/php-fpm.d/*
RUN rm -f /etc/nginx/nginx.conf
RUN rm -f /etc/nginx/conf.d/default.conf
RUN rm -f /usr/local/etc/php-fpm.conf

# Copy glpi build
COPY --from=build_glpi --chown=www-data:www-data ${GLPI_PATHS_ROOT} ${GLPI_PATHS_ROOT}

# Add some configurations files
RUN if [ "$PHP_XDEBUG" = "yes" ] ; then \
        echo "Xdebug is enabled - PHP_XDEBUG=$PHP_XDEBUG"; \
    else \
        rm -f root/etc/php-fpm.d/xdebug.conf.j2 ;\
    fi ;

COPY root/ /
COPY /docker-entrypoint.sh /
COPY /docker-entrypoint.d/* /docker-entrypoint.d/
COPY /php-fpm.conf /usr/local/etc/php-fpm.conf

RUN chmod -R +x /docker-entrypoint.d/ /usr/local/bin/cronwrapper.py \
    && chmod -R g=rX,o=--- /var/www/* \
    && addgroup nginx www-data

EXPOSE 80/tcp
VOLUME ["/var/www/files", "/var/www/config"]
WORKDIR "${GLPI_PATHS_ROOT}"

HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
    CMD curl --silent http://127.0.0.1:80/fpm-ping | grep -q pong || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/bin/supervisord", "--configuration", "/etc/supervisord.conf"]